/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.yakindu.analysis.example;

import hu.bme.mit.yakindu.analysis.IStatemachine;
import hu.bme.mit.yakindu.analysis.ITimerCallback;

public interface IExampleStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseStart();
		
		public void raiseWhiteStep();
		
		public void raiseBlackStep();
		
		public long getWhiteTimeLeft();
		
		public void setWhiteTimeLeft(long value);
		
		public long getBlackTimeLeft();
		
		public void setBlackTimeLeft(long value);
		
	}
	
	public SCInterface getSCInterface();
	
}
